"""
Tests for the Terraform generator module.

This module contains unit tests for the Terraform configuration generator
that converts simulation results into Terraform configuration files.
"""

import pytest
from unittest.mock import patch, MagicMock, mock_open
import json
import os
from pathlib import Path

from leaf_cloud.terraform.generator import TerraformGenerator

# Sample test data
SAMPLE_SIMULATION_RESULTS = {
    "resources": {
        "google_compute_instance": {
            "web_server": {
                "machine_type": "e2-micro",
                "zone": "us-central1-a",
                "boot_disk": {
                    "initialize_params": {
                        "image": "debian-cloud/debian-11"
                    }
                },
                "network_interface": [{
                    "network": "default"
                }]
            }
        },
        "google_storage_bucket": {
            "data_bucket": {
                "name": "test-bucket-123",
                "location": "US"
            }
        }
    },
    "providers": {
        "google": {
            "project": "test-project",
            "region": "us-central1"
        }
    },
    "variables": {
        "instance_count": {
            "type": "number",
            "default": 1,
            "description": "Number of instances to create"
        }
    }
}

SAMPLE_ORIGINAL_RESOURCES = {
    "google_compute_instance.web_server": {
        "type": "google_compute_instance",
        "name": "web_server",
        "config": {
            "machine_type": "n1-standard-1",  # Different from optimized
            "zone": "us-central1-a",
            "boot_disk": {
                "initialize_params": {
                    "image": "debian-cloud/debian-10"  # Different from optimized
                }
            }
        }
    }
}

class TestTerraformGenerator:
    """Test cases for the TerraformGenerator class."""

    def test_init_with_valid_simulation_results(self):
        """Test initialization with valid simulation results."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        assert generator is not None
        assert len(generator.optimized_resources) == 2  # Should have 2 resources
        assert "google_compute_instance.web_server" in generator.optimized_resources
        assert "google_storage_bucket.data_bucket" in generator.optimized_resources

    def test_init_with_original_resources(self):
        """Test initialization with original resources for comparison."""
        generator = TerraformGenerator(
            SAMPLE_SIMULATION_RESULTS,
            original_resources=SAMPLE_ORIGINAL_RESOURCES
        )
        assert generator.original_resources == SAMPLE_ORIGINAL_RESOURCES

    def test_extract_resources_from_simulation(self):
        """Test resource extraction from simulation results."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        resources = generator._extract_resources_from_simulation()
        
        assert len(resources) == 2
        assert "google_compute_instance.web_server" in resources
        assert "google_storage_bucket.data_bucket" in resources
        assert resources["google_compute_instance.web_server"]["config"]["machine_type"] == "e2-micro"

    def test_generate_terraform_config(self):
        """Test generation of complete Terraform configuration."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        config = generator.generate_terraform_config()
        
        assert "# Generated by LEAF-Cloud - Optimized Terraform Configuration" in config
        assert "provider " in config
        assert "google_compute_instance" in config
        assert "google_storage_bucket" in config
        assert "e2-micro" in config  # Verify optimized value is used

    def test_generate_resource_block(self):
        """Test generation of a single resource block."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        resource_type = "google_compute_instance"
        resource_name = "test_instance"
        resource_config = {
            "machine_type": "e2-micro",
            "zone": "us-central1-a"
        }
        
        block = generator.generate_resource_block(
            resource_type, resource_name, resource_config
        )
        
        assert block.startswith(f'resource "{resource_type}" "{resource_name}"')
        assert "machine_type = " in block
        assert "zone = " in block
        assert block.endswith("}\n")

    def test_format_attribute_with_dict(self):
        """Test formatting of dictionary attributes."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        formatted = generator._format_attribute("boot_disk", {
            "initialize_params": {"image": "debian-cloud/debian-11"}
        })
        
        assert "boot_disk" in formatted
        assert "initialize_params" in formatted
        assert "image" in formatted
        assert "debian-cloud/debian-11" in formatted

    def test_format_attribute_with_list(self):
        """Test formatting of list attributes."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        formatted = generator._format_attribute("tags", ["web", "production"])
        assert "tags = [" in formatted
        assert "\"web\"" in formatted
        assert "\"production\"" in formatted

    def test_format_attribute_with_simple_value(self):
        """Test formatting of simple value attributes."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        assert generator._format_attribute("name", "test") == 'name = "test"'
        assert generator._format_attribute("count", 3) == 'count = 3'
        assert generator._format_attribute("enabled", True) == 'enabled = true'
        assert generator._format_attribute("ratio", 0.5) == 'ratio = 0.5'

    @patch('os.makedirs')
    @patch('builtins.open', new_callable=mock_open)
    def test_write_terraform_files(self, mock_file, mock_makedirs):
        """Test writing Terraform configuration to files."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        test_dir = "/test/dir"
        
        # Call the method
        generator.write_terraform_files(test_dir)
        
        # Verify directory creation
        mock_makedirs.assert_called_once_with(test_dir, exist_ok=True)
        
        # Verify files were written
        assert mock_file.call_count >= 2  # At least main.tf and variables.tf
        
        # Check if main.tf was written
        main_tf_call = None
        for call in mock_file.call_args_list:
            if str(call[0][0]).endswith('main.tf'):
                main_tf_call = call
                break
                
        assert main_tf_call is not None, "main.tf was not written"
        assert 'w' in main_tf_call[0][1], "File not opened in write mode"

    def test_get_optimization_changes_with_changes(self):
        """Test getting optimization changes between original and optimized resources."""
        generator = TerraformGenerator(
            SAMPLE_SIMULATION_RESULTS,
            original_resources=SAMPLE_ORIGINAL_RESOURCES
        )
        
        changes = generator.get_optimization_changes()
        
        # Check summary
        assert changes["summary"]["total_resources"] == 2
        assert changes["summary"]["modified_resources"] == 1
        assert changes["summary"]["added_resources"] == 1
        
        # Check specific changes for modified resource
        assert "google_compute_instance.web_server" in changes["resources"]
        assert changes["resources"]["google_compute_instance.web_server"]["action"] == "modified"
        
        # Check added resource
        assert "google_storage_bucket.data_bucket" in changes["resources"]
        assert changes["resources"]["google_storage_bucket.data_bucket"]["action"] == "added"

    def test_get_optimization_changes_no_original(self):
        """Test optimization changes with no original resources."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        changes = generator.get_optimization_changes()
        
        # All resources should be marked as added
        assert changes["summary"]["total_resources"] == 2
        assert changes["summary"]["added_resources"] == 2
        assert changes["summary"]["modified_resources"] == 0
        
    def test_init_with_empty_simulation_results(self):
        """Test initialization with empty simulation results."""
        # The current implementation doesn't raise an error for empty dict
        generator = TerraformGenerator({})
        assert generator.optimized_resources == {}
        
    def test_init_with_invalid_simulation_results(self):
        """Test initialization with invalid simulation results structure."""
        # The current implementation doesn't validate the structure in __init__
        generator = TerraformGenerator({"invalid": "structure"})
        assert generator.optimized_resources == {}  # Empty dict when no resources found

    def test_generate_terraform_config_with_empty_resources(self):
        """Test config generation with empty resources."""
        generator = TerraformGenerator({"resources": {}})
        config = generator.generate_terraform_config()
        assert "# Generated by LEAF-Cloud" in config
        assert "resource " not in config  # No resources should be in the output

    def test_format_attribute_with_none_value(self):
        """Test formatting of None value attributes."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        assert generator._format_attribute("optional", None) == 'optional = null'
        
    def test_generate_optimization_summary(self):
        """Test generation of optimization summary."""
        generator = TerraformGenerator(
            SAMPLE_SIMULATION_RESULTS,
            original_resources=SAMPLE_ORIGINAL_RESOURCES
        )
        
        summary = generator.generate_optimization_summary()
        assert isinstance(summary, str)
        assert "Optimization Summary" in summary
        
    def test_get_resource_improvement_metrics(self):
        """Test getting resource improvement metrics."""
        generator = TerraformGenerator(
            SAMPLE_SIMULATION_RESULTS,
            original_resources=SAMPLE_ORIGINAL_RESOURCES
        )
        
        metrics = generator.get_resource_improvement_metrics()
        assert isinstance(metrics, dict)
        
    def test_write_terraform_files_creates_variables_tf(self):
        """Test that variables.tf is created when variables are present."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        with patch('builtins.open', mock_open()) as mock_file, \
             patch('os.makedirs'):
            generator.write_terraform_files("/test/dir")
            
            # Check if variables.tf was written
            variables_tf_called = any(
                'variables.tf' in str(call[0][0]) 
                for call in mock_file.call_args_list
            )
            assert variables_tf_called, "variables.tf was not written"
            
    def test_write_terraform_files_handles_missing_variables(self):
        """Test that missing variables don't cause errors."""
        # Create a copy without variables
        no_vars = SAMPLE_SIMULATION_RESULTS.copy()
        no_vars.pop('variables', None)
        
        generator = TerraformGenerator(no_vars)
        
        with patch('builtins.open', mock_open()) as mock_file, \
             patch('os.makedirs'):
            # Should not raise any exceptions
            generator.write_terraform_files("/test/dir")
            
    def test_extract_resources_with_flat_structure(self):
        """Test resource extraction with flat resource structure."""
        flat_results = {
            "resources": [
                {
                    "type": "google_compute_instance",
                    "name": "test_instance",
                    "machine_type": "e2-micro"
                },
                {
                    "type": "google_storage_bucket",
                    "name": "test_bucket",
                    "location": "US"
                }
            ]
        }
        
        generator = TerraformGenerator(flat_results)
        assert len(generator.optimized_resources) == 2
        assert "google_compute_instance.test_instance" in generator.optimized_resources
        assert "google_storage_bucket.test_bucket" in generator.optimized_resources
        
    def test_extract_resources_with_invalid_structure(self):
        """Test resource extraction with invalid resource structure."""
        invalid_results = {
            "resources": {
                "invalid_type": "not_a_dict"
            }
        }
        
        generator = TerraformGenerator(invalid_results)
        assert len(generator.optimized_resources) == 0
        
    def test_compare_configs_with_nested_structures(self):
        """Test comparison of nested configurations."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        original = {
            "nested": {
                "key1": "value1",
                "key2": "value2"
            },
            "list": [1, 2, 3]
        }
        
        optimized = {
            "nested": {
                "key1": "value1_modified",
                "key3": "new_value"
            },
            "list": [1, 4, 3]
        }
        
        changes = generator._compare_configs(original, optimized)
        
        # Check nested dictionary changes
        assert "nested.key1" in changes
        assert changes["nested.key1"]["before"] == "value1"
        assert changes["nested.key1"]["after"] == "value1_modified"
        
        # Check removed key
        assert "nested.key2" in changes
        assert changes["nested.key2"]["before"] == "value2"
        assert changes["nested.key2"]["after"] is None
        
        # Check added key
        assert "nested.key3" in changes
        assert changes["nested.key3"]["before"] is None
        assert changes["nested.key3"]["after"] == "new_value"
        
        # Check list changes (should be compared as a whole, not by index)
        assert "list" in changes
        assert changes["list"]["before"] == [1, 2, 3]
        assert changes["list"]["after"] == [1, 4, 3]
        
    def test_generate_terraform_config_with_providers(self):
        """Test config generation with provider configurations."""
        config = {
            "resources": {},
            "providers": {
                "google": {
                    "project": "test-project",
                    "region": "us-central1"
                }
            }
        }
        
        generator = TerraformGenerator(config)
        result = generator.generate_terraform_config()
        
        assert "provider \"google\"" in result
        assert "project = \"test-project\"" in result
        assert "region = \"us-central1\"" in result  # Single space after 'region'
        
    def test_write_terraform_files_with_variables(self, tmp_path):
        """Test writing Terraform files with variables."""
        test_dir = tmp_path / "terraform"
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        generator.write_terraform_files(str(test_dir))
        
        # Check if files were created
        assert (test_dir / "main.tf").exists()
        assert (test_dir / "variables.tf").exists()
        assert (test_dir / "optimization_report.json").exists()
        
        # Check if variables.tf contains the expected content
        variables_content = (test_dir / "variables.tf").read_text()
        assert "variable \"instance_count\"" in variables_content
        assert "description = \"Number of instances to create\"" in variables_content
        assert "type        = number" in variables_content
        assert "default     = 1" in variables_content
        
    def test_extract_resources_with_nested_arrays(self):
        """Test resource extraction with nested array structure."""
        nested_array_results = {
            "resources": [
                {
                    "type": "google_compute_instance",
                    "name": "test_instance",
                    "network_interface": [
                        {
                            "network": "default",
                            "access_config": [
                                {
                                    "nat_ip": ""
                                }
                            ]
                        }
                    ]
                }
            ]
        }
        
        generator = TerraformGenerator(nested_array_results)
        assert len(generator.optimized_resources) == 1
        assert "google_compute_instance.test_instance" in generator.optimized_resources
        
    def test_compare_configs_with_different_types(self):
        """Test comparison of configurations with different types."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        # Test with different types
        changes = generator._compare_configs(
            {"key": 123},
            {"key": "123"}
        )
        assert "key" in changes
        assert changes["key"]["before"] == 123
        assert changes["key"]["after"] == "123"
        
        # Test with None values
        changes = generator._compare_configs(
            {"key": None},
            {"key": "value"}
        )
        assert changes["key"]["before"] is None
        assert changes["key"]["after"] == "value"
        
    def test_write_terraform_files_handles_io_errors(self):
        """Test that IO errors during file writing are handled gracefully."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        # Create a context manager that raises IOError for all file operations
        def mock_open_raises(*args, **kwargs):
            if 'w' in args[1]:  # Only raise on write mode
                raise IOError("Test IO Error")
            return MagicMock()
        
        with patch('builtins.open', side_effect=mock_open_raises), \
             patch('os.makedirs') as mock_makedirs, \
             patch('json.dump') as mock_json_dump:
            
            # Should not raise an exception
            generator.write_terraform_files("/test/dir")
            
            # Verify that makedirs was called
            mock_makedirs.assert_called_once_with("/test/dir", exist_ok=True)
            
            # Verify that json.dump was not called since all file operations should fail
            assert not mock_json_dump.called, "json.dump should not be called when file operations fail"
            
    def test_get_optimization_changes_with_removed_resources(self):
        """Test detection of removed resources in optimization changes."""
        # Create a generator with original resources but empty simulation results
        generator = TerraformGenerator(
            {"resources": {}},
            original_resources={
                "resource.to.be.removed": {
                    "type": "test_resource",
                    "name": "to.be.removed",
                    "config": {"key": "value"}
                }
            }
        )
        
        changes = generator.get_optimization_changes()
        assert changes["summary"]["removed_resources"] == 1
        assert "resource.to.be.removed" in changes["resources"]
        assert changes["resources"]["resource.to.be.removed"]["action"] == "removed"
        
    def test_format_attribute_with_complex_structures(self):
        """Test formatting of complex attribute structures."""
        generator = TerraformGenerator(SAMPLE_SIMULATION_RESULTS)
        
        # Test with nested dictionaries and lists
        result = generator._format_attribute("complex", {
            "nested": {"key": "value"},
            "list": [1, 2, 3],
            "bool": True,
            "none": None
        })
        
        assert "complex" in result
        assert "nested" in result
        assert "list" in result
        assert "bool = true" in result
        assert "none = null" in result
